//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacen
    {
        public int Id_Almacen { get; set; }
        public string NombreAlmacen { get; set; }
        public System.DateTime FechaEntradaProducto { get; set; }
        public System.DateTime FechaSalidaProducto { get; set; }
        public int Id_Productos { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
