//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevolucionProv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DevolucionProv()
        {
            this.Transacciones = new HashSet<Transacciones>();
        }
    
        public int Id_Productos { get; set; }
        public int Cantidad_dep { get; set; }
        public int Producto_dep { get; set; }
        public int Id_DevolucionProv { get; set; }
        public int Id_Cliente { get; set; }
        public System.DateTime FechaDevolucion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacciones> Transacciones { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
