//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deportes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacciones
    {
        public int Id_Trans { get; set; }
        public int Id_Ventas { get; set; }
        public int Id_Productos { get; set; }
        public int Id_DevolucionProv { get; set; }
        public int Id_Comprov { get; set; }
        public int Id_TipoTrans { get; set; }
    
        public virtual CompraProv CompraProv { get; set; }
        public virtual DevolucionProv DevolucionProv { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual TipoTransaccion TipoTransaccion { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
